name: gig_finance_coach
description: AI-powered finance and gig coach for students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  http: ^1.2.1
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
